require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Communities::RoomsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Communities::Room. As you add validations to Communities::Room, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Communities::RoomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all communities_rooms as @communities_rooms" do
      room = Communities::Room.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:communities_rooms)).to eq([room])
    end
  end

  describe "GET show" do
    it "assigns the requested communities_room as @communities_room" do
      room = Communities::Room.create! valid_attributes
      get :show, {:id => room.to_param}, valid_session
      expect(assigns(:communities_room)).to eq(room)
    end
  end

  describe "GET new" do
    it "assigns a new communities_room as @communities_room" do
      get :new, {}, valid_session
      expect(assigns(:communities_room)).to be_a_new(Communities::Room)
    end
  end

  describe "GET edit" do
    it "assigns the requested communities_room as @communities_room" do
      room = Communities::Room.create! valid_attributes
      get :edit, {:id => room.to_param}, valid_session
      expect(assigns(:communities_room)).to eq(room)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Communities::Room" do
        expect {
          post :create, {:communities_room => valid_attributes}, valid_session
        }.to change(Communities::Room, :count).by(1)
      end

      it "assigns a newly created communities_room as @communities_room" do
        post :create, {:communities_room => valid_attributes}, valid_session
        expect(assigns(:communities_room)).to be_a(Communities::Room)
        expect(assigns(:communities_room)).to be_persisted
      end

      it "redirects to the created communities_room" do
        post :create, {:communities_room => valid_attributes}, valid_session
        expect(response).to redirect_to(Communities::Room.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved communities_room as @communities_room" do
        post :create, {:communities_room => invalid_attributes}, valid_session
        expect(assigns(:communities_room)).to be_a_new(Communities::Room)
      end

      it "re-renders the 'new' template" do
        post :create, {:communities_room => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested communities_room" do
        room = Communities::Room.create! valid_attributes
        put :update, {:id => room.to_param, :communities_room => new_attributes}, valid_session
        room.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested communities_room as @communities_room" do
        room = Communities::Room.create! valid_attributes
        put :update, {:id => room.to_param, :communities_room => valid_attributes}, valid_session
        expect(assigns(:communities_room)).to eq(room)
      end

      it "redirects to the communities_room" do
        room = Communities::Room.create! valid_attributes
        put :update, {:id => room.to_param, :communities_room => valid_attributes}, valid_session
        expect(response).to redirect_to(room)
      end
    end

    describe "with invalid params" do
      it "assigns the communities_room as @communities_room" do
        room = Communities::Room.create! valid_attributes
        put :update, {:id => room.to_param, :communities_room => invalid_attributes}, valid_session
        expect(assigns(:communities_room)).to eq(room)
      end

      it "re-renders the 'edit' template" do
        room = Communities::Room.create! valid_attributes
        put :update, {:id => room.to_param, :communities_room => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested communities_room" do
      room = Communities::Room.create! valid_attributes
      expect {
        delete :destroy, {:id => room.to_param}, valid_session
      }.to change(Communities::Room, :count).by(-1)
    end

    it "redirects to the communities_rooms list" do
      room = Communities::Room.create! valid_attributes
      delete :destroy, {:id => room.to_param}, valid_session
      expect(response).to redirect_to(communities_rooms_url)
    end
  end

end
