language: ruby
rvm:
- 2.1.2
services:
- redis-server
- mongodb
env:
- DB=postgresql
bundler_args: "--without production --retry 5"
script:
- bundle exec rake bower:install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
deploy:
  provider: heroku
  api_key: d8e75801-fe0b-404b-94b8-ff0b11fdda4e
  app: sabatora
  on:
    repo: myoo/sabatora
  run:
    - rake db:migrate
before_deploy:
- cp -f .heroku.bowerrc .bowerrc
  
