language: ruby
rvm:
- 2.1.2
services:
- redis-server
- mongodb
env:
- DB=postgresql
bundler_args: "--without production --retry 5"
script:
- bundle exec rake bower:install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: jsxnSeLUChxdNFOz08IqHplE8Cqyjg0+jC8vOdWYm9xpJabwkgMMrG/eGIbW0r7kQnelPuDsPEWl+MbbbJhZNAEUbpJeJRbuamtdq/jo795md78dpdJivy6zp/07nIzodCjNYIrO//edi+jXSymuS6GBlYYO+F6I9bV9XIJlSfE=
  app: sabatora
  on:
    repo: myoo/sabatora
  run:
  - rake db:migrate
