language: ruby
rvm:
- 2.1.2
services:
- redis-server
- mongodb
env:
- DB=postgresql
bundler_args: "--without production --retry 10"
script:
- bundle exec rake bower:install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: LzHe5qRhi+sfhvr9MDYknTvO6LVHKEYW7u3svNGAwDVbW5PEUQMeuJv15C0sk/X/aFRyzMr3k/okRy8EZUcv1PcI64wv8miYR9k51ZXA4cF2hp4gBxiB6BY4HG45ndUhvUfJDXbIq7jClQXu0CCui+TQpVAbV34xtcRceahO6jM=
  app: sabatora
  on:
    repo: myoo/sabatora
  run:
    - rake db:migrate
